meta:
  version: 2
  flow: Classic
  substituting_steps:
    # IO pads are used instead of pins
    #OpenROAD.GlobalPlacementSkipIO: null
    #OpenROAD.IOPlacement: null
    #+OpenROAD.Floorplan: OpenROAD.Padring
    # ECO diodes
    +OpenROAD.GlobalRouting: Odb.InsertECODiodes
    
    # Add Seal Ring
    #+Checker.XOR: KLayout.SealRing
    
    # Run Filler insertion
    # This is done manually for now
    #+KLayout.SealRing: KLayout.FillerGeneration
    
    # We run KLayout minimal DRC afterwards
    KLayout.DRC: null
    Magic.DRC: null
    
    # We use the LEFs without obstruction
    # later on for extraction
    Magic.SpiceExtraction: null
    
    # Magic reports some overlaps
    # I think the padring has some overlapping cells
    # but the GDS looks alright
    Checker.IllegalOverlap: null
    
    # We run our own LVS after OpenLane
    Netgen.LVS: null
    
    Magic.WriteLEF: null # writes empty lef
    Odb.CheckDesignAntennaProperties: null # requires LEF

    # IHP uses cumulative antenna rules
    # which aren't supported in repair yet
    OpenROAD.RepairAntennas: null
    
    # Errors out due to some
    # the sv -> v conversion
    Verilator.Lint: null
    
    # Some warnings in the SoC
    # GL simulation is fine
    Checker.YosysSynthChecks: null
    
    # Setup violations don't matter (for now)
    Checker.SetupViolations: null

DESIGN_NAME: greyhound_ihp
VERILOG_FILES:
- dir::src/greyhound_ihp.sv
- dir::src/soc/greyhound_soc.v
- dir::src/soc/cv32e40x_clock_gate.sv
- dir::ip/EF_QSPI_XIP_CTRL/hdl/rtl/EF_QSPI_XIP_CTRL.v
- dir::ip/EF_QSPI_XIP_CTRL/hdl/rtl/DMC.v
- dir::ip/EF_QSPI_XIP_CTRL/hdl/rtl/bus_wrappers/EF_QSPI_XIP_CTRL_AHBL.v
- dir::ip/EF_PSRAM_CTRL/hdl/rtl/EF_PSRAM_CTRL.v
- dir::ip/EF_PSRAM_CTRL/hdl/rtl/bus_wrapper/EF_PSRAM_CTRL_AHBL.v
- dir::ip/EF_UART/hdl/rtl/EF_UART.v
- dir::ip/EF_UART/hdl/rtl/bus_wrappers/EF_UART_AHBL.v
- dir::ip/EF_IP_UTIL/hdl/ef_util_lib.v

VERILOG_DEFINES:
- FUNCTIONAL

# Magic has an offset on the SRAMs
PRIMARY_GDSII_STREAMOUT_TOOL: klayout
# Save on file space by sharing same cells
KLAYOUT_CONFLICT_RESOLUTION: SkipNewCell

# Bondpad is not yet included in the PDK
EXTRA_GDS:
- dir::ip/bondpad/bondpad_70x70.gds

EXTRA_LEFS:
- dir::ip/bondpad/bondpad_70x70.lef

# SDC
#PNR_SDC_FILE: dir::constraint.sdc
#SIGNOFF_SDC_FILE: dir::constraint.sdc
#FALLBACK_SDC: dir::constraint.sdc

# Power nets
VDD_NETS:
- VDD
GND_NETS:
- VSS

# Perform extraction using the LEF/DEF
MAGIC_EXT_USE_GDS: false

# The IO cells do not extract properly yet
MAGIC_EXT_ABSTRACT_CELLS:
- bondpad_70x70
- sg13g2_IOPadInOut30mA
- sg13g2_IOPadIn
- sg13g2_IOPadOut30mA
- sg13g2_IOPadIOVdd
- sg13g2_IOPadIOVss
- sg13g2_IOPadVss
- sg13g2_IOPadVdd

# Due to thin core area ring
GRT_ALLOW_CONGESTION: true

CLOCK_NET: clk_i
CLOCK_PERIOD: 20
CTS_OBSTRUCTION_AWARE: true

# Floorplanning
FP_SIZING: absolute
DIE_AREA:  [   0.00,   0.00, 3600.00, 5000.00 ]
CORE_AREA: [ 362, 362, 3238, 4638 ]
FP_OBSTRUCTIONS:
- [362, 1060.5, 3238, 4638] # top area
PL_TARGET_DENSITY_PCT: 43

# TopMetal2 obstructions for the logo
# Metal5 obstructions to prevent PDN from doing sth stupid between the SRAMs
PDN_OBSTRUCTIONS:
 - [TopMetal2, 450, 450, 900, 900]
 - [Metal5, 2901.5, 1298.41, 3237.96, 1312.95]
 - [Metal5, 2901.5, 1549.75, 3237.96, 1564.29]
 - [Metal5, 2901.5, 1801.09, 3237.96, 1815.63]
 - [Metal5, 2901.5, 2052.43, 3237.96, 2066.97]
 - [Metal5, 2901.5, 2303.77, 3237.96, 2318.31]
 - [Metal5, 2901.5, 2555.11, 3237.96, 2569.65]
 - [Metal5, 2901.5, 2806.45, 3237.96, 2820.99]
 - [Metal5, 2901.5, 3057.79, 3237.96, 3072.33]
 - [Metal5, 2901.5, 3309.13, 3237.96, 3323.67]
 - [Metal5, 2901.5, 3560.47, 3237.96, 3575.01]
 - [Metal5, 2901.5, 3811.81, 3237.96, 3826.35]
 - [Metal5, 2901.5, 4063.15, 3237.96, 4077.69]
 - [Metal5, 2901.5, 4314.49, 3237.96, 4329.03]
 - [Metal5, 2901.5, 4565.83, 3237.96, 4580.37]
ROUTING_OBSTRUCTIONS:
 - [TopMetal2, 450, 450, 900, 900]
 - [Metal5, 2905, 1065, 3235, 4564]

# Don't insert buffers between eFPGA and SRAMs
RSZ_DONT_TOUCH_RX: "fabric_wrapper.fabric_sram.*"

# Time driven placement ignores don't touch directives
# Therefore only enable routability driven
PL_TIME_DRIVEN: False
PL_ROUTABILITY_DRIVEN: True

# PDN
FP_PDN_CFG: dir::pdn.tcl

# Padring

MACROS:
  
  # We can't add the logo as a macro, as otherwise
  # there will be an obstruction for stdcell placement
  #greyhound_logo:
  #  gds:
  #    - dir::logo/greyhound/greyhound_logo_drawing.gds
  #  lef:
  #    - dir::logo/greyhound/greyhound_logo.lef
  #  nl:
  #    - dir::logo/greyhound/greyhound_logo.v
  #  instances: 
  #    i_greyhound_logo:
  #      location: [450, 450]
  #      orientation: N

    
  RM_IHPSG13_1P_1024x16_c2_bm_bist:
    gds:
      - pdk_dir::libs.ref/sg13g2_sram/gds/RM_IHPSG13_1P_1024x16_c2_bm_bist.gds
    lef:
      - pdk_dir::libs.ref/sg13g2_sram/lef/RM_IHPSG13_1P_1024x16_c2_bm_bist.lef
    nl:
      - pdk_dir::libs.ref/sg13g2_sram/verilog/RM_IHPSG13_1P_1024x16_c2_bm_bist.v
    lib:
      "nom_typ_1p20V_25C":
        - pdk_dir::libs.ref/sg13g2_sram/lib/RM_IHPSG13_1P_1024x16_c2_bm_bist_typ_1p20V_25C.lib
      "nom_fast_1p32V_m40C":
        - pdk_dir::libs.ref/sg13g2_sram/lib/RM_IHPSG13_1P_1024x16_c2_bm_bist_fast_1p32V_m55C.lib
      "nom_slow_1p08V_125C":
        - pdk_dir::libs.ref/sg13g2_sram/lib/RM_IHPSG13_1P_1024x16_c2_bm_bist_slow_1p08V_125C.lib
    instances:
      i_soc_sram0_0:
        location: [969.5, 363.9]
        orientation: W
      i_soc_sram0_1:
        location: [1498, 363.9]
        orientation: E
      i_soc_sram1_0:
        location: [1840, 363.9]
        orientation: W
      i_soc_sram1_1:
        location: [2368.5, 363.9]
        orientation: E

PDN_MACRO_CONNECTIONS:
  - "i_soc_sram0_0 VDD VSS VDD! VSS!"
  - "i_soc_sram0_0 VDD VSS VDDARRAY! VSS!"
  - "i_soc_sram0_1 VDD VSS VDD! VSS!"
  - "i_soc_sram0_1 VDD VSS VDDARRAY! VSS!"
  - "i_soc_sram1_0 VDD VSS VDD! VSS!"
  - "i_soc_sram1_0 VDD VSS VDDARRAY! VSS!"
  - "i_soc_sram1_1 VDD VSS VDD! VSS!"
  - "i_soc_sram1_1 VDD VSS VDDARRAY! VSS!"

DIODE_CELL: sg13g2_antennanp/A

